#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=1

install_dir=""

config_load tailscale
config_get install_dir "common" "install_dir"

file_check () {
	if [ ! -f $install_dir/tailscale ]; then
		arch=`uname -m`
		if [ "$arch" == "mips" ]; then
			endianness=`echo -n I | hexdump -o | awk '{ print (substr($2,6,1)=="1") ? "le" : ""; exit }'`
		elif [ "$arch" == "armv7l" ]; then
			arch=arm
		elif [ "$arch" == "aarch64" ]; then
			arch=arm64
		elif [ "$arch" == "x86_64" ]; then
			arch=amd64
		fi

		tailscale_version=""

		latest_version=`wget -O- https://pkgs.tailscale.com/stable/ | grep tailscale_ | head -1 | cut -d'_' -f 2`
		if [ "$tailscale_version" != "$latest_version" ]; then
			tailscale_version=$latest_version
		fi

		version="${tailscale_version}_${arch}${endianness}"

		echo "Downloading Tailscale ${version} .."

		echo -e "tailscale_${version}/tailscale" > /tmp/tailscale_${version}_files.txt
		echo -e "tailscale_${version}/tailscaled" >> /tmp/tailscale_${version}_files.txt

		wget -O- https://pkgs.tailscale.com/stable/tailscale_${version}.tgz | tar x -zvf - -C /tmp -T /tmp/tailscale_${version}_files.txt

		mv /tmp/tailscale_$version/* $install_dir
		rm -rf /tmp/tailscale_${version}*

		echo "Done!"
	fi
}

start_derper () {
	local cfg="$1"
	local val

	config_get_bool val "$cfg" 'disabled' '0'
	[ "$val" = 1 ] && return 1

	echo "start derper ..."
	procd_open_instance
	procd_set_param command  $install_dir/derper
	config_get val "$cfg" "hostname"
	procd_append_param command --hostname=$val
	config_get val "$cfg" "conf_file" "/etc/derper.conf"
	procd_append_param command -c=$val
	config_get val "$cfg" "https_porta" "12345"
	procd_append_param command -a :$val
	config_get val "$cfg" "http_port" "-1"
	procd_append_param command -http-port $val
	config_get val "$cfg" "certdir"
	procd_append_param command -certdir $val
	config_get val "$cfg" "certmode"
	procd_append_param command -certmode $val
	config_get val "$cfg" "stun" "true"
	procd_append_param command -stun=$val
	config_get val "$cfg" "verify_clients" "false"
	procd_append_param command --verify-clients=$val

	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

start_tailscaled() {
	local cfg="$1"
	local val

	config_get_bool val "$cfg" 'disabled' '0'
	[ "$val" = 1 ] && return 1

	file_check

	procd_open_instance
	procd_set_param command $install_dir/tailscaled
	config_get val "$cfg" "port" "41461"
	procd_append_param command --port $val
	procd_append_param command --state /etc/config/tailscaled.state
	procd_append_param command --statedir /etc/tailscale/

	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

start_service() {
	config_foreach start_tailscaled tailscaled
	config_foreach start_derper derper
}

stop_service() {
  /usr/bin/tailscaled --cleanup
  killall -9 derper
}
